on:
  create:
    tags:
      - '*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: c-hive/gha-yarn-cache@v2
      - run: yarn
      - run: yarn test
      - run: yarn build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/main.js
            dist/styles.css
            dist/license.txt
            dist/versions.json
            dist/manifest.json
